name: mix_generators
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=3.10.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  build:
  source_gen:

  mix_annotations:
    path: ../mix_annotations/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:

flutter:
